#/etc/fail2ban/filter.d/vaultwarden.conf
[Definition]
failregex = ^.*Username or password is incorrect\. Try again\. IP: <HOST>\..*$
            ^.*Invalid admin token\. IP: <HOST>\..*$
ignoreregex =
